repos:

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0 # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: [] # optional args

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: trailing-whitespace
        files: "(app)|(tests)"
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

# Formatters

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        args: [
          "--diff",
          "--check"
        ]
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        require_serial: true
        args: [
          "--diff",
          "--check-only"
        ]
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [
          -r,
          --in-place,
          --quote="
        ]
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

# Linters

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        args: [--config=.flake8]
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args: [
          --rcfile=.pylintrc.toml
        ]
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        exclude: "(app/models/domain)|(app/models/data_schemas)|(devops/aws)"
