{
 "title": "POC",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DQGate",
    "query": {}
   },
   {
    "name": "DQCheckName",
    "query": {}
   },
   {
    "name": "subarea",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "chunk",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "ingested" }
  ]
 },
 "panels": [
  { "title": "Dynamic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "\"$searchable_pattern\" Rate per Check",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(DQCheckName) (rate({DQGateName=\"$DQGate\"} |~ `(?i)$searchable_pattern` [1h])) * 100"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({DQGateName=\"$DQGate\"} |~ `(?i)$searchable_pattern` [$__interval])) * 100) / sum(count_over_time({DQGateName=\"$DQGate\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern records per Gate",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\"} |~ `(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  { "title": "Basic stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data source",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{DQGateName=\"$DQGate\", DQCheckName=\"$DQCheckName\", Subarea=\"$subarea\", DataChunk=\"$chunk\"} |= ``"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical per Sub-area",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(Subarea) (count_over_time({DQGateName=\"$DQGate\"} [$__interval]))",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\", DQCheckName=\"$DQCheckName\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count extracted records per Gate",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\"} |~ `extracted` [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count processed records per Gate",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\"} |~ `processed` [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count ingested records per Gate",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\"} |~ `ingested` [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count failed records per Gate",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({DQGateName=\"$DQGate\"} |~ `failed` [$__interval]))"
    }
   ]
  },
  { "title": "Donuts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ingested by DQCheckName",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(DQCheckName) (count_over_time({DQGateName=\"$DQGate\"} |~ `ingested` [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed by CheckName",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(DQCheckName) (count_over_time({DQGateName=\"$DQGate\"} |~ `failed` [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed by Subarea",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Subarea) (count_over_time({DQGateName=\"$DQGate\"} |~ `failed` [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}